const members=[
{id:'david',name:'David',role:'新房项目 · 统筹规划',image:'david.jpg',brief:'把图纸变成有序的施工计划，也把每个细节说清楚。',bio:'从最初的点位讨论到施工安排，David 的人物展示围绕新房电气规划展开。用清晰的沟通串联屋主、设计与施工环节，让你知道每一步正在发生什么。',skills:['新房电气规划','全屋点位讨论','施工进度协调'],motto:'好的开始，是先听懂你想要怎样的家。',service:'工地新房整包'},
{id:'petter',name:'petter',role:'电器安装 · 细节控',image:'petter.jpg',brief:'一盏灯、一只开关，细小的安装也值得认真对待。',bio:'petter 的人物展示聚焦家用电器与灯具安装。在开始前了解设备需求、使用习惯和空间布局，再一起讨论合适的安装位置与实施安排。',skills:['灯具与开关','厨房电器安装','使用习惯沟通'],motto:'顺手的生活，藏在那些不起眼的细节里。',service:'电器安装'},
{id:'daniel',name:'daniel',role:'电路维修 · 耐心排查',image:'daniel.jpg',brief:'复杂的问题慢慢梳理，让你知道发生了什么、下一步怎么做。',bio:'daniel 的人物展示聚焦家庭电路问题的沟通与排查。认真记录异常发生的时间、位置和设备情况，把专业问题解释得容易理解，让维修过程更有条理。',skills:['故障信息梳理','家庭电路检修','维修方案沟通'],motto:'把问题讲明白，安心就多一点。',service:'家庭电路维修'},
{id:'sun',name:'Sun',role:'旧房改造 · 空间焕新',image:'sun.jpg',brief:'尊重老房子的故事，也为新的生活方式留出空间。',bio:'Sun 的人物展示围绕旧房电气改造展开。结合房屋现有条件与未来的生活需求，一起讨论线路更新、插座调整与照明方案，让变化有计划地发生。',skills:['旧房线路规划','点位重新布局','装修协同'],motto:'熟悉的家，也可以有新的可能。',service:'旧房改造'},
{id:'sky',name:'sky',role:'灯光设计 · 生活氛围',image:'sky.jpg',brief:'关注光落下的地方，让日常生活多一点舒适与温度。',bio:'sky 的人物展示聚焦住宅照明与日常使用体验。从阅读角落到厨房工作区，讨论亮度、色温与开关布局，让灯光真正配合你的生活。',skills:['住宅灯光沟通','场景照明','灯具安装规划'],motto:'让每一盏灯，都亮在你需要的地方。',service:'电器安装'}
];
const $=s=>document.querySelector(s);
const gallery=$('#team-gallery');
if(gallery)gallery.innerHTML=members.map(m=>`<a class="person" href="team/${m.id}.html" aria-label="查看 ${m.name} 人物详情"><div class="portrait-frame"><img src="assets/${m.image}" alt="${m.name} 人物展示用素材肖像，非本人照片" loading="lazy" width="480" height="680"><div class="portrait-reveal">${m.brief}<span>认识 ${m.name} ↗</span></div></div><div class="person-label"><h3>${m.name}</h3><small>${m.role}</small><span>↗</span></div></a>`).join('');
const profile=$('#profile-content');
if(profile){const i=members.findIndex(m=>m.id===document.body.dataset.member);const m=members[i];if(m){document.title=`${m.name} · 人物档案 | HARBOURLINE ELECTRICAL 港湾电气`;const next=members[(i+1)%members.length];profile.innerHTML=`<div class="breadcrumb"><a href="../index.html">首页</a><span>/</span><a href="../index.html#team">认识团队</a><span>/</span><span>${m.name}</span></div><div class="profile-layout"><div class="profile-image"><img src="../assets/${m.image}" alt="${m.name} 展示用素材肖像，非本人照片"><small>概念肖像 · 非本人照片</small></div><div class="profile-copy"><p class="small-label">MEET YOUR ELECTRICIAN</p><h1>${m.name}</h1><p class="profile-role">${m.role}</p><p class="profile-bio">${m.bio}</p><h2>可以一起聊聊</h2><div class="tags">${m.skills.map(s=>`<span>${s}</span>`).join('')}</div><p class="profile-motto">“${m.motto}”</p><a class="button peach" href="../index.html?member=${encodeURIComponent(m.name)}&service=${encodeURIComponent(m.service)}#quote">与 ${m.name} 聊项目 <span>↗</span></a><p class="profile-notice">首版人物分工及介绍为示意，真实履历、执业信息与档期需在正式上线前确认。</p></div></div><div class="profile-nav"><a href="../index.html#team">← 返回人物相册</a><a href="${next.id}.html">下一位：${next.name} →</a></div>`}}
const menu=$('.menu-button');if(menu){menu.addEventListener('click',()=>{const nav=$('.header nav');const open=nav.classList.toggle('open');menu.setAttribute('aria-expanded',String(open));menu.setAttribute('aria-label',open?'收起导航':'展开导航')});document.querySelectorAll('.header nav a').forEach(a=>a.addEventListener('click',()=>{$('.header nav').classList.remove('open');menu.setAttribute('aria-expanded','false');menu.setAttribute('aria-label','展开导航')}))}
function openDialog(dialog){if(!dialog||dialog.open)return;dialog.showModal();document.body.classList.add('modal-open')}
function closeDialog(dialog){dialog.close()}
document.querySelectorAll('dialog').forEach(dialog=>{dialog.querySelectorAll('.dialog-close').forEach(b=>b.addEventListener('click',()=>closeDialog(dialog)));dialog.addEventListener('click',e=>{if(e.target===dialog){const b=dialog.getBoundingClientRect();if(e.clientX<b.left||e.clientX>b.right||e.clientY<b.top||e.clientY>b.bottom)closeDialog(dialog)}});dialog.addEventListener('close',()=>{document.body.classList.remove('modal-open');if(dialog.id==='welcome-dialog'){try{sessionStorage.setItem('harbourline-welcomed','yes')}catch{}}})});
const welcome=$('#welcome-dialog');if(welcome){let seen=false;try{seen=sessionStorage.getItem('harbourline-welcomed')==='yes'}catch{}if(!seen&&!location.hash)openDialog(welcome);$('#enter-site').addEventListener('click',()=>closeDialog(welcome));$('#show-welcome').addEventListener('click',()=>openDialog(welcome))}
document.querySelectorAll('[data-policy]').forEach(b=>b.addEventListener('click',()=>{const privacy=b.dataset.policy==='privacy';$('#policy-title').textContent=privacy?'隐私说明':'使用说明';$('#policy-text').textContent=privacy?'当前展示版不会将表单信息发送至服务器，也不会持久保存咨询内容。欢迎提示使用当前会话的浏览器存储记录是否已看过。下载清单由浏览器在本地生成，请自行妥善保管。页面图片均在本地提供，不使用第三方追踪。':'本网站为住宅电工服务的设计演示。人物照片为素材肖像，人物介绍与分工为示意，不代表真实执业资质、项目经历或服务承诺。表单只能生成本地咨询清单，不构成正式预约或报价。正式上线前需确认公司资料、团队信息、服务地区与联系方式。';openDialog($('#policy-dialog'))}));
const form=$('#quote-form');let lastSummary='';
if(form){const params=new URLSearchParams(location.search);for(const key of ['member','service']){const val=params.get(key);if(val&&[...form.elements[key].options].some(o=>o.value===val))form.elements[key].value=val}document.querySelectorAll('[data-service]').forEach(b=>b.addEventListener('click',()=>{form.elements.service.value=b.dataset.service;$('#quote').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});setTimeout(()=>form.elements.name.focus({preventScroll:true}),350)}));form.addEventListener('input',()=>{$('#form-result').hidden=true;lastSummary=''});form.addEventListener('submit',e=>{e.preventDefault();for(const field of form.querySelectorAll('input,textarea')){field.value=field.value.trim();field.setCustomValidity(field.required&&!field.value?'请填写此项，不能只输入空格。':'')}if(!form.reportValidity())return;const d=new FormData(form);lastSummary=`HARBOURLINE ELECTRICAL · 港湾电气咨询清单\n\n服务类型：${d.get('service')}\n称呼：${d.get('name')}\n所在区域：${d.get('area')}\n电子邮箱：${d.get('email')}\n希望沟通的成员：${d.get('member')}\n\n项目需求：\n${d.get('message')}\n\n说明：此清单由展示版生成，尚未发送，不构成预约或报价。`;$('#quote-summary').textContent=lastSummary;$('#form-result').hidden=false;$('#form-result').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth',block:'nearest'})});form.querySelectorAll('input,textarea').forEach(f=>f.addEventListener('input',()=>f.setCustomValidity('')));$('#download-quote').addEventListener('click',()=>{if(!lastSummary)return;const blob=new Blob(['\uFEFF'+lastSummary],{type:'text/plain;charset=utf-8'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='港湾电气-咨询需求清单.txt';document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1000)})}
// A slow, circuit-like light path connects the photographic texture to the electrical identity.
const canvas=$('#current-canvas');if(canvas){const ctx=canvas.getContext('2d');if(ctx){const reduce=matchMedia('(prefers-reduced-motion: reduce)');let width=0,height=0,frame=0,visible=true;function resize(){const r=canvas.getBoundingClientRect(),dpr=Math.min(devicePixelRatio||1,2);width=r.width;height=r.height;canvas.width=width*dpr;canvas.height=height*dpr;ctx.setTransform(dpr,0,0,dpr,0,0);draw(0)}function draw(t){ctx.clearRect(0,0,width,height);const center=width*(width<760?.80:.77),cy=height*.46;for(let j=0;j<5;j++){ctx.beginPath();const rx=width*(.12+j*.016),ry=height*(.32+j*.026);ctx.ellipse(center,cy,rx,ry,-.24,-Math.PI*.85,Math.PI*.94);ctx.strokeStyle=`rgba(237,181,164,${.045+j*.009})`;ctx.lineWidth=.8;ctx.stroke()}if(width>600){const p=(t*.000055)%(Math.PI*2),rx=width*.17,ry=height*.39;const x=center+Math.cos(p)*rx,y=cy+Math.sin(p)*ry;const glow=ctx.createRadialGradient(x,y,0,x,y,36);glow.addColorStop(0,'rgba(237,181,164,.38)');glow.addColorStop(1,'rgba(237,181,164,0)');ctx.fillStyle=glow;ctx.beginPath();ctx.arc(x,y,36,0,Math.PI*2);ctx.fill()}}function loop(t){draw(t);if(visible&&!reduce.matches&&!document.hidden)frame=requestAnimationFrame(loop)}function sync(){cancelAnimationFrame(frame);draw(0);if(visible&&!reduce.matches&&!document.hidden)frame=requestAnimationFrame(loop)}resize();new ResizeObserver(resize).observe(canvas);new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;sync()}).observe(canvas);reduce.addEventListener('change',sync);document.addEventListener('visibilitychange',sync)}}

